version: '3.8'

services:
  tiffin-service:
    container_name: tiffin-service
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true  # Fixes file changes not detected inside Docker
    stdin_open: true
    tty: true

    networks:
      - mynetwork

networks:
  mynetwork:
    external: true
