name: Backend CI

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  backend-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create Docker Network
        run: docker network create mynetwork || true

      - name: Start Backend and Mongo
        working-directory: backend
        run: docker-compose up -d --build

      - name: Health Check Backend
        run: |
          echo "Waiting for backend..."
          sleep 10
          curl -f http://localhost:5000 || (echo "Backend not reachable!" && exit 1)

      - name: Cleanup
        if: always()
        working-directory: backend
        run: docker-compose down
