name: Frontend CI

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  frontend-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create Docker Network
        run: docker network create mynetwork || true
       
       # OPTIONAL: Only needed if you want to use legacy `docker-compose`
      - name: Install Docker Compose (Legacy)
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" \
          -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
           docker-compose version

      - name: Start Frontend
        working-directory: frontend
        run: docker-compose up -d --build

      - name: Health Check Frontend
        run: |
          echo "Waiting for frontend..."
          sleep 10
          curl -f http://localhost:3000 || (echo "Frontend not reachable!" && exit 1)

      - name: Cleanup
        if: always()
        working-directory: frontend
        run: docker-compose down
